#!/bin/csh
#set designSynPath = "~/Workarea/pulp/pulpenix/src/ips/riscv/design_syn/"
set curDir = "`pwd`"
set dateNtime = "`date +"%d%m%H%M"`"
set dc_shellCommandsFile = $RISCV_PULP_SW_UTILS/dc_shellCommandsFile.txt
set dc_shellCommandsFileTemplate = $RISCV_PULP_SW_UTILS/dc_shellCommandsFile_template.txt

python $RISCV_PULP_SW_UTILS/parseUser.py -sf $dc_shellCommandsFileTemplate -df $dc_shellCommandsFile
cd $RISCV_DESIGN_SYN
dc_shell-t -f $dc_shellCommandsFile
mv synthTemp.ddc synth$dateNtime.ddc
cd $curDir
